version: '2'
services:
  redis:
    image: redis
    #        command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - ./redis-data:/data/
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/thrive-market
    depends_on:
      - redis

  swaggerui:
    image: swaggerapi/swagger-ui
    ports:
      - 5001:8080
    volumes:
      - ./swagger.json:/usr/share/nginx/html/swagger.json
    depends_on:
      - web
